# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JavaTutor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JavaTutor
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'JavaTutorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JavaTutorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
